### ISSUE TITLE
Revisit Definition of what is a Game

### ISSUE THREAD

**Issue by OkelleyDevelopment** [HammerAPI/TwoPlayerGames#81]
Revisit the fourth rule of the game set up to allow us to include the graph coloring game otherwise, our current understanding of the GCG will not satisfy our requirements.

**Comment by OkelleyDevelopment** [comment]
Old: "If no legal move is available and the board is not colored, Player 2 wins."

Now we could move to a new section

"If either player cant move, player 2 wins" and this will allow for the graph coloring game to be added

**Comment by dannyhammer** [comment]
Break research into sections: Each section has its own set of rules that define a game.
